[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 8081
  framework = "#custom"

[[redirects]]
  from = "/api/football"
  to = "/.netlify/functions/football"
  status = 200

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]  